cmake_minimum_required(VERSION 3.16)
project(file_hero LANGUAGES CXX)
add_executable(file-hero-core native/main.cpp)
target_compile_features(file-hero-core PRIVATE cxx_std_17)
if(MSVC)
  target_compile_options(file-hero-core PRIVATE /utf-8 /W4)
elseif(MINGW)
  target_link_options(file-hero-core PRIVATE -municode -static)
endif()
