const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
process.chdir(path.join(__dirname, '..'));
fs.mkdirSync('build', { recursive: true });
const win = process.platform === 'win32';
const compiler = process.env.CXX || (win && fs.existsSync('C:/msys64/mingw64/bin/g++.exe') ? 'C:/msys64/mingw64/bin/g++.exe' : 'g++');
const result = spawnSync(compiler, ['-std=c++17', '-O2', '-Wall', '-Wextra', ...(win ? ['-municode', '-static'] : []), 'native/main.cpp', '-o', `build/file-hero-core${win ? '.exe' : ''}`], { stdio: 'inherit' });
if (result.error) console.error('Install a C++17 compiler or set CXX:', result.error.message);
process.exit(result.status ?? 1);
